name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.5

    - name: Install dependencies
      run: |
        cd src
        dotnet restore

    - name: Build
      run: |
        cd src
        dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        cd src
        dotnet test --no-restore --verbosity normal

    - name: Pack
      run: |
        cd src
        dotnet pack

    - name: Publish
      run: |
        cd src
        dotnet nuget push -k ${{secrets.NUGET_API_KEY}}
